Website/OperatorApp/urls.py
from django.urls import path 

from . import views 

app_name = 'operator'

urlpatterns = [
    path('', views.operator_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.operator_logout, name='logout'),
    path('edit/', views.edit_profile, name='edit'),
    path('operators/', views.operators, name='operators'),
    path('api/operator/', views.OperatorView.as_view()),
    path('api/mode/', views.ModeView.as_view()),
]

Website/OperatorWebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('OperatorApp.urls')),
    path('admin/', admin.site.urls),
]

Website/OperatorApp/models.py
from django.contrib.auth.models import User
from django.db import models


class Operator(models.Model):
    admin = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    modes = models.ManyToManyField('Mode')
    homepage = models.URLField()
    api_url = models.URLField()
    default_language = models.CharField(default='English', max_length=40)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    active = models.BooleanField(default=True)
    miptaurl = models.URLField()


    def __str__(self):
        return self.name



class Mode(models.Model):
    short_desc = models.CharField(max_length=50)
    long_desc = models.CharField(max_length=8000, null=True)

    def __str__(self):
        return self.short_desc

Website/OperatorApp/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from .models import Mode, Operator

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-group'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-group'}))

    def clean(self):
        user_name = self.cleaned_data['username']
        pw = self.cleaned_data['password']

        # check the user exists
        if not User.objects.filter(username=user_name).exists():
            raise forms.ValidationError("This user does not exist.")
        
        # check user's authentication details are correct
        if not authenticate(username=user_name, password=pw):
            raise forms.ValidationError("Invalid login details.")

        return self.cleaned_data


class OperatorForm(forms.ModelForm):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}), disabled=True)
    modes = forms.ModelMultipleChoiceField(
        queryset=Mode.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'id':'modes'}),
    )
    homepage = forms.URLField(required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    api_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    miptaurl = forms.URLField(required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    default_language = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    phone = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    active = forms.BooleanField(required=False)

    class Meta:
        model = Operator
        fields = ['name', 'modes', 'homepage', 'api_url', 'miptaurl', 'default_language', 'phone', 'email', 'active']
        
        
class RegisterForm(forms.ModelForm):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    
    operator_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    modes = forms.ModelMultipleChoiceField(
        queryset=Mode.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'id':'modes'}),
    )
    homepage = forms.URLField(required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    api_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    miptaurl = forms.URLField(required=False, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    phone = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control'}))
    
    def clean(self):
        uname = self.cleaned_data['username']
        password1 = self.cleaned_data['password']
        password2 = self.cleaned_data['confirm_password']
        name = self.cleaned_data['operator_name']
        modes = self.cleaned_data['modes']
        homepage = self.cleaned_data['homepage']
        api_url = self.cleaned_data['api_url']
        miptaurl = self.cleaned_data['miptaurl']
        phone = self.cleaned_data['phone']
        email = self.cleaned_data['email'].strip()

        # check the user does not exist
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError("This username is already taken.")
            
        # check the operator name does not exist
        if User.objects.filter(username=name).exists():
            raise forms.ValidationError("This operator name is already taken.")
        
        # check the passwords match
        if not password1 == password2:
            raise forms.ValidationError("The passwords do not match.")

        return self.cleaned_data
        
    def save(self, commit=True):
        m = super(RegisterForm, self).save(commit=False)
        m.username = self.cleaned_data['username']
        m.password = self.cleaned_data['password']
        if commit:
            m.save()
        return m

    class Meta:
        model = User
        fields = ('username', 'password', 'confirm_password', 'operator_name', 'modes', 'api_url', 'miptaurl', 'phone', 'email')

    

Website/OperatorApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.messages import success
from django.views import View
from django.core.serializers import serialize
from django.contrib import messages

from .forms import LoginForm, OperatorForm, RegisterForm
from OperatorApp.models import Operator, Mode
from .Hypercat import hypercat

'''
Checks the data that comes inside params: /api/<params>
checks the pk value sent and returns specified operator
also checks for invalid/no pk values and returns entire list 
'''


class OperatorView(View):

    # OperatorAPI GET /operator view - returns registered operators in PAS212:2016
    # compliant format
    def get(self, request):
        params = list(request.GET.items())
        operators_list = Operator.objects.all()
        if params and (params[0][0] == 'filterString'):
            if params[0][1] == "all":
                pass
            else:
                operators_list = Operator.objects.filter(pk=params[0][1])
        serialized_operators = sorted(serialize('python', operators_list), key=lambda x: x['pk']    )
        hc = hypercat.createOperatorHypercat(serialized_operators, Mode.objects.all())
        return JsonResponse(hc, safe=False)


class ModeView(View):

    # Returns list of correctly formatted modes
    def clean_modes(self, modes):
        cleaned_modes = []
        for mode in modes:
            cleaned_modes.append({'id': mode['pk'], 'short_desc': mode['fields']['short_desc'],
                                  'long_desc': mode['fields']['long_desc']})

        return cleaned_modes

    # OperatorAPI GET /mode view - returns available modes of transport
    def get(self, request):
        params = list(request.GET.items())
        modes_list = Mode.objects.all()
        if params and (params[0][0] == 'filterString'):
            modes_list = Mode.objects.filter(pk=params[0][1])
        serialized_operators = serialize('python', modes_list)
        data = self.clean_modes(serialized_operators)
        return JsonResponse(data, safe=False)


# Register view
def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            # Create new operator object
            newop_name = user_form.cleaned_data['operator_name']
            newop_homepage = user_form.cleaned_data['homepage']
            newop_api_url = user_form.cleaned_data['api_url']
            newop_miptaurl = user_form.cleaned_data['miptaurl']
            newop_modes = user_form.cleaned_data['modes']
            newop_phone = user_form.cleaned_data['phone']
            newop_email = user_form.cleaned_data['email']
            newop = Operator.objects.create(admin=User.objects.get(username=user.username), name=newop_name, homepage=newop_homepage, api_url=newop_api_url, miptaurl=newop_miptaurl, phone=newop_phone, email=newop_email)
            newop.modes.set(newop_modes)

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            success(request, f"Congratulations, {user.username}! You've registered successfully!")
            return redirect(reverse('operator:operators'))
        else:
            print(user_form.errors)
    else:
        user_form = RegisterForm()

    context = {
        'registration_form': user_form,
    }
    return render(request, 'OperatorApp/register.html', context)


# Login view
def operator_login(request):
    # If the user is logged in, redirect to the operators page
    if request.user.is_authenticated:
        return redirect(reverse('operator:operators'))

    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        # Validate and clean form
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            login(request, user)

            return redirect(reverse('operator:edit'))

    return render(request, 'OperatorApp/login.html', {"form": form})


# Logout - redirect to login page
def operator_logout(request):
    logout(request)
    return redirect(reverse('operator:login'))


# Edit operator profile
def edit_profile(request):
    # If the user is not logged in, redirect to the login page
    if not request.user.is_authenticated:
        return redirect('operator:login')

    operator = Operator.objects.get(admin=request.user)
    form = OperatorForm(instance=operator)
    if request.method == 'POST':
        form = OperatorForm(request.POST, instance=operator)
        # Validate form
        if form.is_valid():
            form.save()
            messages.success(request, "Operator updated successfully.")
            return redirect(reverse('operator:edit'))

    return render(request, 'OperatorApp/edit-operator.html', {'form': form})


# Display all operators in a table (after an operator logs in)
def operators(request):
    # If the user is not logged in, redirect to the login page
    if not request.user.is_authenticated:
        return redirect('operator:login')

    operator_info = Operator.objects.order_by('pk')
    context_dict = {'operators': operator_info}

    return render(request, 'OperatorApp/operators.html', context_dict)

Website/OperatorApp/templates/OperatorApp/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head lang="en">
        <!-- Required meta tags -->
    	<meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

        <title>
        	Open Transport |
            {% block title %}
            {% endblock %}
        </title>
    </head>
    
	<!-- Navbar -->
	<body>
        <nav class="navbar navbar-expand-md navbar-expand-lg navbar-dark bg-dark sticky-top" >
            <a class="navbar-brand" href="{% url 'operator:operators' %}">Open Transport</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'operator:operators' %}">Operators</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'operator:edit' %}">Edit Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'operator:logout' %}">Log Out</a>
                        </li> 
                    </ul>
                </div>
			{% else %}
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'operator:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'operator:register' %}">Register</a>
                        </li>
                    </ul>
                </div>

            {% endif %}

        </nav>

        <div class="container">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible col-lg-12">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            
            {% block content %}

            {% endblock %}
        </div>

        <!-- jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

        {% block js %}

        {% endblock %}
    </body>
</html>

Website/OperatorApp/templates/OperatorApp/edit-operator.html
{% extends 'OperatorApp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit
{% endblock %}

{% block content %}

<div class="container">

  <h1 class="text-center my-4">Edit Operator</h1>

  <table class="card table mx-auto" style="width: 25em;">
      <form method='post' action="{% url 'operator:edit' %}">
          {% csrf_token %}
          <tr>
              <th>
          {% for field in form %}
              {% if field.label != 'Modes' %}
              {{ field.label }}: {{ field }}
              {% endif %}
              {% endfor %}
              </th>
            <th>
                {{ form.modes.label }}
                <br/>
          {% for field in form.modes %}
                <span style="font-weight:normal">{{ field }}</span><br/>
              {% endfor %}
            </th>
          </tr>
          <th class="text-center" colspan="2">
              <button type="submit" class="btn btn-md btn-primary">Save</button>
          </th>
      </form>
    </table>
  </div>

{% endblock %}
  

Website/OperatorApp/templates/OperatorApp/login.html
{% extends 'OperatorApp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}


<!-- Display a form for logging in -->
{% block content %}
<div class="container">
    <h1 class="text-center my-4">Login</h1>
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-body">
            <form id="login_form" method="post" action="{% url 'operator:login' %}">
                {% csrf_token %}
    
                {{ form|crispy }}
                <div class="text-center">
                    <input type="submit" class="btn btn-md btn-primary" value="Log in" />
                </div>
            </form>
        </div>
    </div>
    

</div>

{% endblock %}

Website/OperatorApp/templates/OperatorApp/operators.html
{% extends 'OperatorApp/base.html' %}

{% block title %}
    Operators
{% endblock %}

<!-- This template will display all operators after an operator logs in-->
{% block content %}
  <div class="container ">
      <h1 class="text-center my-4">Operators</h1>
      {% if operators %}
      <div class="table-responsive-xl">
        <div class="d-flex justify-content-center">
        <table class="table table-striped table-hover">
          <tbody>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Modes</th>
              <th>Homepage</th>
              <th>API URL & MIPTA URL</th>
              <th>Language</th>
              <th>Phone number</th>
              <th>Email Address</th>
              <th>Active</th>
            </tr>
  
            {% for operator in operators %}
            <tr>
              <td>{{ operator.id }}</td>
              <td style="white-space: nowrap;">{{ operator.name }}</td>
              <td>
                <ul>
                  {% for mode in operator.modes.all %}
                  <li>{{ mode }}</li>
                  {% endfor %}
                </ul>
              </td>
              <td>{{operator.homepage}}</td>
              <td>{{operator.api_url}} {{operator.miptaurl}}</td>
              <td>{{operator.default_language}}</td>
              <td>{{operator.phone}}</td>
              <td>{{operator.email}}</td>
              <td>{{operator.active}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
          <<strong>There are no operators</strong>
        {% endif %}
          </div>
      </div>

  </div>

{% endblock %}

Website/OperatorApp/templates/OperatorApp/register.html
{% extends 'OperatorApp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center my-4">Register</h1>
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-body">
            <form id="login_form" method="post" action="{% url 'operator:register' %}">
                {% csrf_token %}

                {{ registration_form|crispy }}
                <div class="text-center">
					<br>
                    <input type="submit" class="btn btn-md btn-primary" value="Register" />
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}